[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/question.py"
name = "Quiz"
icon = "ğŸ“"

[[pages]]
path = "pages/dashboard.py"
name = "ëŒ€ì‰¬ë³´ë“œ"
icon = "ğŸ“Š"

[[pages]]
path = "pages/agora.py"
name = "ì§ˆë¬¸"
icon = "ğŸ’¬"
